### ISSUE TITLE
hacktoberfest TODO: Asuka assets

### ISSUE THREAD

**Issue by JWW127** [JWW127/tokyo-3#6]
# Need assets for Asuka
These will be the assets the app will render to the terminal after timer is up. keep in mind do to the nature of terminals we a limited to 80x80 (characters spaces), large images will be shrunk. The image will also appear pixelated due to the same factors previously indicated.

## Specifications for asset
- jpg format
- at least 2 images, and less than 6
- must be SFW
- file size must be less than 10kb(each)
- dimensions should be 80x80 or 160x160 depending on if you can meet the required < 10kb
- If you are having trouble getting it below 10kb without ruining the image try [sqoosh](https://squoosh.app/)
- create a branch, with a name appropriate to the feature you are working on
- place them in the directory /images/asuka (you have to make the asuka directory)
- create a pull request

**Comment by Such6** [comment]
can you give a sample of an asuka asset

**Comment by JWW127** [comment]
You can find an example of the current assets in the images/ directory of the project. If you aren't sure of who Asuka is, you'll  have to google "Asuka Evangelion" as this is a Evangelion themed project.

**Comment by Such6** [comment]
Thank you for you appreciation, let me know if I can contribute on any other issues too.
