### ISSUE TITLE
hacktoberfest TODO: Seele Assets

### ISSUE THREAD

**Issue by JWW127** [JWW127/tokyo-3#7]
# Need assets for Seele
These will be the assets the app will render to the terminal after timer is up. keep in mind do to the nature of terminals we a limited to 80x80 (characters spaces), large images will be shrunk. The image will also appear pixelated due to the same factors previously indicated.

## Specifications for asset
- jpg format
- at least 2 images, and less than 6
- must be SFW
- file size must be less than 10kb(each)
- dimensions should be 80x80 or 160x160 depending on if you can meet the required < 10kb
- If you are having trouble getting it below 10kb without ruining the image try [sqoosh](https://squoosh.app/)
- create a branch, with a name appropriate to the feature you are working on
- place them in the directory /images/seele (you have to make the seele directory)
- create a pull request

**Comment by alsd4git** [comment]
I can do that, can you assign me the issue?

**Comment by JWW127** [comment]
I'll assign you the Seele one for now. If nobody goes for the other one, I'll assign you that one too. I don't want you to get in trouble with any of the Hacktoberfest rules. Thank You BTW.
