### ISSUE TITLE
hacktoberfest TODO: Kaworu Assets

### ISSUE THREAD

**Issue by JWW127** [JWW127/tokyo-3#8]
# Need assets for Kaworu
These will be the assets the app will render to the terminal after timer is up. keep in mind do to the nature of terminals we a limited to 80x80 (characters spaces), large images will be shrunk. The image will also appear pixelated due to the same factors previously indicated.

## Specifications for asset
- jpg format
- at least 2 images, and less than 6
- must be SFW
- file size must be less than 10kb(each)
- dimensions should be 80x80 or 160x160 depending on if you can meet the required < 10kb
- If you are having trouble getting it below 10kb without ruining the image try [sqoosh](https://squoosh.app/)
- create a branch, with a name appropriate to the feature you are working on
- place them in the directory /images/Kaworu (you have to make the kaworu directory)
- create a pull request

**Comment by alsd4git** [comment]
I can work on that

**Comment by Such6** [comment]
Can you give more details or sample of kaworu asset, I would like to work on this

**Comment by JWW127** [comment]
The details of both Kaworu and Asuka can be found by googling "Evangelion Characters" examples of what the project target asset should resemble can be found in the images/ directory of the project.

**Comment by alsd4git** [comment]
thanks for the assing, I will work on in tonight
